// ❌ DO NOT add 'use client' here
import './globals.css';
import ClientLayout from './ClientLayout';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <head>
        {/* viewport penting untuk mobile */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
